apiVersion: v1
kind: Service
metadata:
  name: voting-sys-election-service
  namespace: monitoring
  labels:
    app: voting-sys-election
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      protocol: TCP
  selector:
    app:  voting-sys-election